let SKILL_SEAL = [
  { "name": "Atk Ploy 1", "effect": "At start of turn, all foes in cardinal directions with Res 1 or more lower than unit suffer Atk-3 until the end of foe's next action.", "icon": "18-12" },
  { "name": "Atk Ploy 2", "effect": "At start of turn, all foes in cardinal directions with Res 1 or more lower than unit suffer Atk-4 until the end of foe's next action.", "icon": "19-0" },
  { "name": "Atk Ploy 3", "effect": "At start of turn, all foes in cardinal directions with Res 1 or more lower than unit suffer Atk-5 until the end of foe's next action.", "icon": "19-1" },
  {	"name": "Attack +1", "effect": "Grants Atk+1.", "stats": {"atk": 1}, "icon": "0-7" },
  {	"name": "Attack +2", "effect": "Grants Atk+2.", "stats": {"atk": 2}, "icon": "0-8" },
  {	"name": "Attack +3", "effect": "Grants Atk+3.", "stats": {"atk": 3}, "icon": "0-9" },
  { "name": "Atk Smoke 1", "effect": "After combat, inflicts Atk-3 on foes within 2 spaces of target through their next actions.", "icon": "26-8" },
  { "name": "Atk Smoke 2", "effect": "After combat, inflicts Atk-5 on foes within 2 spaces of target through their next actions.", "icon": "26-9" },
  { "name": "Atk Smoke 3", "effect": "After combat, inflicts Atk-7 on foes within 2 spaces of target through their next actions.", "icon": "26-10" },
  { "name": "Brash Assault 1", "effect": "Unit automatically makes a follow-up when at HP ≤ 30% and attacking a foe that can counter.", "icon": "6-0"},
  { "name": "Brash Assault 2", "effect": "Unit automatically makes a follow-up when at HP ≤ 40% and attacking a foe that can counter.", "icon": "6-1"},
  { "name": "Brash Assault 3", "effect": "Unit automatically makes a follow-up when at HP ≤ 50% and attacking a foe that can counter.", "icon": "6-2"},
  { "name": "Breath of Life 1", "effect": "If unit initiates attack, adjacent allies recover 3 HP after combat.", "icon": "10-2"},
  { "name": "Breath of Life 2", "effect": "If unit initiates attack, adjacent allies recover 5 HP after combat.", "icon": "10-3"},
  { "name": "Breath of Life 3", "effect": "If unit initiates attack, adjacent allies recover 7 HP after combat.", "icon": "10-4"},
  { "name": "Close Def 1", "effect": "If unit is attacked by foe using sword, axe, lance, or dragonstone, unit receives Def/Res+2 during combat.", "icon": "19-10" },
  { "name": "Close Def 2", "effect": "If unit is attacked by foe using sword, axe, lance, or dragonstone, unit receives Def/Res+4 during combat.", "icon": "19-11" },
  { "name": "Close Def 3", "effect": "If unit is attacked by foe using sword, axe, lance, or dragonstone, unit receives Def/Res+6 during combat.", "icon": "19-12" },
  { "name": "Defense +1", "effect": "Grants Def+1.", "stats": {"def": 1}, "icon": "1-0" },
  { "name": "Defense +2", "effect": "Grants Def+2.", "stats": {"def": 2}, "icon": "1-1" },
  { "name": "Defense +3", "effect": "Grants Def+3.", "stats": {"def": 1}, "icon": "1-2" },
  { "name": "Deflect Magic 1", "effect": "If unit receives consecutive attacks from a foe using magic, damage from second attack onward reduced by 30%.", "icon": "29-5" },
  { "name": "Deflect Magic 2", "effect": "If unit receives consecutive attacks from a foe using magic, damage from second attack onward reduced by 50%.", "icon": "29-6" },
  { "name": "Deflect Magic 3", "effect": "If unit receives consecutive attacks from a foe using magic, damage from second attack onward reduced by 80%.", "icon": "29-7" },
  { "name": "Deflect Melee 1", "effect": "If unit receives consecutive attacks from a foe using a sword, lance, or axe, damage from second attack onward reduced by 30%.", "icon": "28-11" },
  { "name": "Deflect Melee 2", "effect": "If unit receives consecutive attacks from a foe using a sword, lance, or axe, damage from second attack onward reduced by 50%.", "icon": "28-12" },
  { "name": "Deflect Melee 3", "effect": "If unit receives consecutive attacks from a foe using a sword, lance, or axe, damage from second attack onward reduced by 80%.", "icon": "29-1" },
  { "name": "Deflect Missile 1", "effect": "If unit receives consecutive attacks from a foe using a bow or dagger, damage from second attack onward reduced by 30%.", "icon": "29-2" },
  { "name": "Deflect Missile 2", "effect": "If unit receives consecutive attacks from a foe using a bow or dagger, damage from second attack onward reduced by 50%.", "icon": "29-3" },
  { "name": "Deflect Missile 3", "effect": "If unit receives consecutive attacks from a foe using a bow or dagger, damage from second attack onward reduced by 80%.", "icon": "29-4" },
  { "name": "Distant Def 1", "effect": "If unit is attacked by foe using bow, daggers, magic, or staff, unit receives Def/Res+2 during combat.", "icon": "16-10" },
  { "name": "Distant Def 2", "effect": "If unit is attacked by foe using bow, daggers, magic, or staff, unit receives Def/Res+4 during combat.", "icon": "16-11" },
  { "name": "Distant Def 3", "effect": "If unit is attacked by foe using bow, daggers, magic, or staff, unit receives Def/Res+6 during combat.", "icon": "16-12" },
  { "name": "Embla's Ward", "effect": "Unit receives 0 damage.", "include": [ {"name": "Veronica"} ], "icon": "16-9" },
  { "name": "Fortify Def 1", "effect": "Grants adjacent allies Def+2 through their next actions at the start of each turn.", "icon": "12-6" },
  { "name": "Fortify Def 2", "effect": "Grants adjacent allies Def+3 through their next actions at the start of each turn.", "icon": "12-7" },
  { "name": "Fortify Def 3", "effect": "Grants adjacent allies Def+4 through their next actions at the start of each turn.", "icon": "12-8" },
  { "name": "Fortify Res 1", "effect": "Grants adjacent allies Res+2 through their next actions at the start of each turn.", "icon": "12-9" },
  { "name": "Fortify Res 2", "effect": "Grants adjacent allies Res+3 through their next actions at the start of each turn.", "icon": "12-10" },
  { "name": "Fortify Res 3", "effect": "Grants adjacent allies Res+4 through their next actions at the start of each turn.", "icon": "12-11" },
  { "name": "Guidance 1", "effect": "If unit has 100% HP, infantry and armored allies within 2 spaces can move to a space adjacent to unit.", "include": [{"moveType": "Flying"}], "icon": "25-8" },
  { "name": "Guidance 2", "effect": "If unit has ≥ 50% HP, infantry and armored allies within 2 spaces can move to a space adjacent to unit.", "include": [{"moveType": "Flying"}], "icon": "25-9" },
  { "name": "Guidance 3", "effect": "Infantry and armored allies within 2 spaces can move to a space adjacent to unit.", "include": [{"moveType": "Flying"}], "icon": "25-10" },
  { "name": "HP +3", "effect": "Grants +3 to max HP.", "stats": {"hp": 3}, "icon": "4" },
  { "name": "HP +4", "effect": "Grants +4 to max HP.", "stats": {"hp": 4}, "icon": "5" },
  { "name": "HP +5", "effect": "Grants +5 to max HP.", "stats": {"hp": 5}, "icon": "6" },
  { "name": "Hardy Bearing 1", "effect": "Disables skills that change unit's attack priority. If unit has 100% HP at start of battle, enemy skills that change attack priority are also disabled.", "icon": "24-8" },
  { "name": "Hardy Bearing 2", "effect": "Disables skills that change unit's attack priority. If unit has ≥ 50% HP at start of battle, enemy skills that change attack priority are also disabled.", "icon": "24-9" },
  { "name": "Hardy Bearing 3", "effect": "Disables skills that change unit's attack priority. Enemy skills that change attack priority are also disabled.", "icon": "24-10" },
  { "name": "Hone Spd 1", "effect": "Grants adjacent allies Spd+2 through their next actions at the start of each turn.", "icon": "12-3"},
  { "name": "Hone Spd 2", "effect": "Grants adjacent allies Spd+3 through their next actions at the start of each turn.", "icon": "12-4"},
  { "name": "Hone Spd 3", "effect": "Grants adjacent allies Spd+4 through their next actions at the start of each turn.", "icon": "12-5"},
  { "name": "Múspellflame", "effect": "Unit receives 0 damage.", "include": [{"name": "Surtr"}], "icon": "33-6"},
  { "name": "Panic Ploy 1", "effect": "At start of turn, bonuses become penalties on all foes in cardinal directions with HP 5 or more lower than unit through foe's next action.", "icon": "19-2"},
  { "name": "Panic Ploy 2", "effect": "At start of turn, bonuses become penalties on all foes in cardinal directions with HP 3 or more lower than unit through foe's next action.", "icon": "19-3"},
  { "name": "Panic Ploy 3", "effect": "At start of turn, bonuses become penalties on all foes in cardinal directions with HP 1 or more lower than unit through foe's next action.", "icon": "19-4"},
  { "name": "Phantom Spd 1", "effect": "When any skill compares this unit's Spd stat to another unit's, this unit's Spd stat is counted as +5 over actual value.", "icon": "20-11" },
  { "name": "Phantom Spd 2", "effect": "When any skill compares this unit's Spd stat to another unit's, this unit's Spd stat is counted as +8 over actual value.", "icon": "20-12" },
  { "name": "Phantom Spd 3", "effect": "When any skill compares this unit's Spd stat to another unit's, this unit's Spd stat is counted as +10 over actual value.", "icon": "21-0" },
  { "name": "Quickened Pulse", "effect": "Special cooldown count -1 at start of Turn 1.", "icon": "18-4" },
  { "name": "Resistance +1", "effect": "Grants Res+1.", "stats": {"res": 1}, "icon": "1-3" },
  { "name": "Resistance +2", "effect": "Grants Res+2.", "stats": {"res": 2}, "icon": "1-4" },
  { "name": "Resistance +3", "effect": "Grants Res+3.", "stats": {"res": 1}, "icon": "1-5" },
  { "name": "Savage Blow 1", "effect": "If unit initiates attack, foes within 2 spaces of target take 3 damage after combat.", "icon": "10-5" },
  { "name": "Savage Blow 2", "effect": "If unit initiates attack, foes within 2 spaces of target take 5 damage after combat.", "icon": "10-6" },
  { "name": "Savage Blow 3", "effect": "If unit initiates attack, foes within 2 spaces of target take 7 damage after combat.", "icon": "10-7" },
  { "name": "Speed +1", "effect": "Grants Spd+1.", "stats": {"spd": 1}, "icon": "0-10"},
  { "name": "Speed +2", "effect": "Grants Spd+2.", "stats": {"spd": 2}, "icon": "0-11"},
  { "name": "Speed +3", "effect": "Grants Spd+3.", "stats": {"spd": 3}, "icon": "0-12"},
  { "name": "Spur Atk 1", "effect": "Grants adjacent allies Atk+2 during combat.", "icon": "10-8" },
  { "name": "Spur Atk 2", "effect": "Grants adjacent allies Atk+3 during combat.", "icon": "10-9" },
  { "name": "Spur Atk 3", "effect": "Grants adjacent allies Atk+4 during combat.", "icon": "10-10" },
  { "name": "Spur Def 1", "effect": "Grants adjacent allies Def+2 during combat.", "icon": "11-1" },
  { "name": "Spur Def 2", "effect": "Grants adjacent allies Def+3 during combat.", "icon": "11-2" },
  { "name": "Spur Def 3", "effect": "Grants adjacent allies Def+4 during combat.", "icon": "11-3" },
  { "name": "Spur Res 1", "effect": "Grants adjacent allies Res+2 during combat.", "icon": "11-4" },
  { "name": "Spur Res 2", "effect": "Grants adjacent allies Res+3 during combat.", "icon": "11-5" },
  { "name": "Spur Res 3", "effect": "Grants adjacent allies Res+4 during combat.", "icon": "11-6" },
  { "name": "Spur Spd 1", "effect": "Grants adjacent allies Spd+2 during combat.", "icon": "10-11" },
  { "name": "Spur Spd 2", "effect": "Grants adjacent allies Spd+3 during combat.", "icon": "10-12" },
  { "name": "Spur Spd 3", "effect": "Grants adjacent allies Spd+4 during combat.", "icon": "11-1" },
  { "name": "Squad Ace A 1", "effect": "Grants HP+3.", "stats": {"hp": 3}, "icon": "21-1" },
  { "name": "Squad Ace A 2", "effect": "Grants HP+4.", "stats": {"hp": 4}, "icon": "21-2" },
  { "name": "Squad Ace A 3", "effect": "Grants HP+5.", "stats": {"hp": 5}, "icon": "21-3" },
  { "name": "Squad Ace B 1", "effect": "Grants Def+1.", "stats": {"def": 1}, "icon": "21-4" },
  { "name": "Squad Ace B 2", "effect": "Grants Def+2.", "stats": {"def": 2}, "icon": "21-5" },
  { "name": "Squad Ace B 3", "effect": "Grants Def+3.", "stats": {"def": 3}, "icon": "21-6" },
  { "name": "Squad Ace C 1", "effect": "Grants Res+1.", "stats": {"res": 1}, "icon": "21-7" },
  { "name": "Squad Ace C 2", "effect": "Grants Res+2.", "stats": {"res": 2}, "icon": "21-8" },
  { "name": "Squad Ace C 3", "effect": "Grants Res+3.", "stats": {"res": 3}, "icon": "21-9" },
  { "name": "Squad Ace D 1", "effect": "Grants Spd+1.", "stats": {"spd": 1}, "icon": "21-10" },
  { "name": "Squad Ace D 2", "effect": "Grants Spd+2.", "stats": {"spd": 2}, "icon": "21-11" },
  { "name": "Squad Ace D 3", "effect": "Grants Spd+3.", "stats": {"spd": 3}, "icon": "21-12"},
  { "name": "Squad Ace E 1", "effect": "Grants Atk+1.", "stats": {"atk": 1}, "icon": "22-0" },
  { "name": "Squad Ace E 2", "effect": "Grants Atk+2.", "stats": {"atk": 2}, "icon": "22-1" },
  { "name": "Squad Ace E 3", "effect": "Grants Atk+3.", "stats": {"atk": 3}, "icon": "22-2" }
];
