const BANNERS = [
  {
    "date": "December 2017",
    "banners": [
      {
        "name": "Happy New Year!",
        "latestHeroesDate": "",
        "startDate": "Dec 31, 2018",
        "focusHeroes": [ "Azura (Happy New Year!)", "Camilla (Happy New Year!)", "Takumi (Happy New Year!)" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Raven & Lucius's Battle",
        "latestHeroesDate": "",
        "startDate": "Dec 30, 2017",
        "focusHeroes": [ "Raven", "Lucius", "Priscilla" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Legendary Heroes: Gunnthrá, Voice of Dreams",
        "latestHeroesDate": "",
        "startDate": "Dec 28, 2017",
        "focusHeroes": [ "Gunnthrá", "Amelia", "Chrom (Spring Festival)", "Fjorm", "Lucina (Spring Festival)", "Charlotte (Bridal Blessings)",
            "Ryoma", "Sigurd", "Roy (Brave Heroes)", "Elise", "Innes", "Lyn (Bridal Blessings)"],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 34,
        "rateRarity4": 58,
        "rateRarity5": 0,
        "rateRarityFocus": 8,
        "pityRateRarity5": 0,
        "pityRateRarityFocus": 0.5
      },
      {
        "name": "A Gift of Peace Tempest Trials",
        "latestHeroesDate": "",
        "startDate": "Dec 22, 2017",
        "focusHeroes": [ "Nowi", "Frederick", "Lucina" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Weapons to Refine, Part 2",
        "latestHeroesDate": "",
        "startDate": "Dec 21, 2017",
        "focusHeroes": [ "Jaffar", "Minerva", "Eldigan" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Winter's Envoy",
        "latestHeroesDate": "",
        "startDate": "Dec 18, 2017",
        "focusHeroes": [ "Lissa (Winter's Envoy)", "Chrom (Winter's Envoy)", "Robin (M) (Winter's Envoy)", "Tharja (Winter's Envoy)" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Tana and Amelia's Battle",
        "latestHeroesDate": "",
        "startDate": "Dec 14, 2017",
        "focusHeroes": [ "Tana", "Amelia", "Eirika" ],
        "excludeFromRarity4": [ "Soleil" ],
        "excludeFromRarity5": [ "Soleil", "Siegbert", "Shiro" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Weapons to Refine",
        "latestHeroesDate": "",
        "startDate": "Dec 07, 2017",
        "focusHeroes": [ "Ephraim", "Lyn", "Takumi" ],
        "excludeFromRarity4": [ "Soleil" ],
        "excludeFromRarity5": [ "Rhajat", "Soleil", "Siegbert", "Shiro" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Children of Fate",
        "latestHeroesDate": "",
        "startDate": "Dec 04, 2017",
        "focusHeroes": [ "Soleil", "Siegbert", "Shiro" ],
        "excludeFromRarity4": [ "Soleil" ],
        "excludeFromRarity5": [ "Rhajat" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Enduring Love, Block B",
        "latestHeroesDate": "",
        "startDate": "Dec 02, 2017",
        "focusHeroes": [ "Dorcas", "Catria", "Sigurd", "Katarina" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [ "Rhajat" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Enduring Love, Block A",
        "latestHeroesDate": "",
        "startDate": "Dec 02, 2017",
        "focusHeroes": [ "Rhajat", "Priscilla", "Tharja", "Faye" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [ "Rhajat" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      }
    ]
  },
  {
    "date": "November 2017",
    "banners": [
      {
        "name": "Legendary Heroes: Fjorm, Princess of Ice",
        "latestHeroesDate": "",
        "startDate": "Nov 27, 2017",
        "focusHeroes": [ "Celica", "Ike", "Ayra", "Caeda (Bridal Blessings)", "Xander (Spring Festival)", "Fjorm", "Deirdre", "Hector", "Camilla (Spring Festival)", "Cordelia (Bridal Blessings)", "Lyn (Brave Heroes)", "Genny" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 34,
        "rateRarity4": 58,
        "rateRarity5": 0,
        "rateRarityFocus": 8,
        "pityRateRarity5": 0,
        "pityRateRarityFocus": 0.5
      },
      {
        "name": "Skills That Boost Special Damage",
        "latestHeroesDate": "",
        "startDate": "Nov 23, 2017",
        "focusHeroes": [ "Karel", "Sonya", "Nephenee" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [ "Dorcas", "Lute", "Mia" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Less Than Heroic Tempest Trials",
        "latestHeroesDate": "",
        "startDate": "Nov 18, 2017",
        "focusHeroes": [ "Ike (Brave Heroes)", "Lyn (Brave Heroes)", "Roy (Brave Heroes)", "Lucina (Brave Heroes)" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [ "Dorcas", "Lute", "Mia" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Takumi and Hinoka's Battle",
        "latestHeroesDate": "",
        "startDate": "Nov 16, 2017",
        "focusHeroes": [ "Takumi", "Hinoka", "Sakura" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [ "Dorcas", "Lute", "Mia" ],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Farfetched Heroes",
        "latestHeroesDate": "",
        "startDate": "Nov 15, 2017",
        "focusHeroes": [ "Dorcas", "Lute", "Mia" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Heroes with Death Blow",
        "latestHeroesDate": "",
        "startDate": "Nov 08, 2017",
        "focusHeroes": [ "Delthea", "Elincia", "Klein" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Long-Haired Gents",
        "latestHeroesDate": "",
        "startDate": "Nov 02, 2017",
        "focusHeroes": [ "Takumi", "Karel", "Ryoma", "Soren" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Short-Haired Ladies",
        "latestHeroesDate": "",
        "startDate": "Nov 02, 2017",
        "focusHeroes": [ "Amelia", "Hinoka", "Shanna", "Katarina" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
    ]
  },
  {
    "date": "October 2017",
    "banners": [
      {
        "name": "Trick or Defeat!",
        "latestHeroesDate": "",
        "startDate": "Oct 30, 2017",
        "focusHeroes": [ "Sakura (Trick or Defeat!)", "Jakob (Trick or Defeat!)", "Henry (Trick or Defeat!)", "Nowi (Trick or Defeat!)" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Flier Boost Skills",
        "latestHeroesDate": "",
        "startDate": "Oct 24, 2017",
        "focusHeroes": [ "Hinoka", "Minerva", "Caeda" ],
        "excludeFromRarity4": ["Tailtiu"],
        "excludeFromRarity5": ["Ayra", "Deirdre", "Tailtiu", "Sigurd"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Genealogy of Light Tempest Trials",
        "latestHeroesDate": "",
        "startDate": "Oct 19, 2017",
        "focusHeroes": [ "Ayra", "Eldigan", "Lachesis" ],
        "excludeFromRarity4": ["Tailtiu"],
        "excludeFromRarity5": ["Deirdre", "Tailtiu", "Sigurd"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "World of Holy War",
        "latestHeroesDate": "",
        "startDate": "Oct 16, 2017",
        "focusHeroes": [ "Deirdre", "Tailtiu", "Sigurd" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Minerva and Maria's Battle",
        "latestHeroesDate": "",
        "startDate": "Oct 11, 2017",
        "focusHeroes": [ "Minerva", "Maria", "Palla" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "The Blood of Dragons Block B",
        "latestHeroesDate": "",
        "startDate": "Oct 05, 2017",
        "focusHeroes": [ "Tiki (Adult)", "Nowi", "Corrin (F)", "Sophia" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "The Blood of Dragons Block A",
        "latestHeroesDate": "",
        "startDate": "Oct 05, 2017",
        "focusHeroes": [ "Tiki (Young)", "Fae", "Ninian", "Corrin (M)" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Heroes with Threaten Spd",
        "latestHeroesDate": "",
        "startDate": "Oct 03, 2017",
        "focusHeroes": [ "Jaffar", "Shanna", "Takumi" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      }
    ]
  },
  {
    "date": "September 2017",
    "banners": [
      {
        "name": "Performing Arts",
        "latestHeroesDate": "",
        "startDate": "Sep 29, 2017",
        "focusHeroes": [ "Olivia (Performing Arts)", "Inigo (Performing Arts)", "Azura (Performing Arts)", "Shigure (Performing Arts)" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Ninian and Hawkeye's Battle",
        "latestHeroesDate": "",
        "startDate": "Sep 20, 2017",
        "focusHeroes": [ "Ninian", "Hawkeye", "Eliwood" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": ["Nephenee", "Oscar", "Elincia"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Moment of Fate Tempest Trials",
        "latestHeroesDate": "",
        "startDate": "Sep 19, 2017",
        "focusHeroes": [ "Ike", "Mist", "Soren", "Titania" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": ["Nephenee", "Oscar", "Elincia"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Heroes with Death Blow",
        "latestHeroesDate": "",
        "startDate": "Sep 18, 2017",
        "focusHeroes": [ "Klein", "Effie", "Hawkeye" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": ["Nephenee", "Oscar", "Elincia"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Dauntless Crimeans",
        "latestHeroesDate": "",
        "startDate": "Sep 15, 2017",
        "focusHeroes": [ "Nephenee", "Oscar", "Elincia" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Ephraim and Eirika's Battle",
        "latestHeroesDate": "",
        "startDate": "Sep 07, 2017",
        "focusHeroes": [ "Ephraim", "Eirika", "Seth" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": ["Lucina (Brave Heroes)", "Roy (Brave Heroes)", "Lyn (Brave Heroes)", "Ike (Brave Heroes)"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "To Die on the Battlefield Tempest Trials Mini",
        "latestHeroesDate": "",
        "startDate": "Sep 05, 2017",
        "focusHeroes": [ "Eliwood", "Lyn", "Ninian", "Hector" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": ["Lucina (Brave Heroes)", "Roy (Brave Heroes)", "Lyn (Brave Heroes)", "Ike (Brave Heroes)"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      },
      {
        "name": "Heroes with Threaten Def",
        "latestHeroesDate": "",
        "startDate": "Sep 04, 2017",
        "focusHeroes": [ "Ephraim", "Peri", "Raven" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": ["Lucina (Brave Heroes)", "Roy (Brave Heroes)", "Lyn (Brave Heroes)", "Ike (Brave Heroes)"],
        "rateRarity3": 36,
        "rateRarity4": 58,
        "rateRarity5": 3,
        "rateRarityFocus": 3,
        "pityRateRarity5": 0.25,
        "pityRateRarityFocus": 0.25
      }
    ]
  },
  {
    "date": "December 0",
    "banners": [
      {
        "name": "Our Lord and Savior",
        "latestHeroesDate": "",
        "startDate": "Feb 01, 2017",
        "focusHeroes": [ "Wrys" ],
        "excludeFromRarity4": [],
        "excludeFromRarity5": [],
        "rateRarity3": 0,
        "rateRarity4": 0,
        "rateRarity5": 0,
        "rateRarityFocus": 100,
        "pityRateRarity5": 0,
        "pityRateRarityFocus": 0
      }
    ]
  }
];
