module.exports = {
  SELECT_BANNER: '#select-banner',
  FOCUS_LIST: '#focus-list',
  SUMMON_OPTION: '.summon-option',
  SUMMON_ORB: '.summon-orb',
  SUMMON_ALL: '#summon-all',
  SUMMON_TABLE: '#summon-table',
  NEW_SESSION: '#new-session',
  RATE_INPUT: '.rate-input > input',
  RATE_INPUT_FOCUS: '#rate-input-focus',
  RATE_INPUT_FOCUS_4: '#rate-input-focus-4',
  RATE_INPUT_5: '#rate-input-5',
  RATE_INPUT_4: '#rate-input-4',
  RATE_INPUT_3: '#rate-input-3',
  CUSTOM_INPUT_FOCUS: '#custom-input-focus',
  CUSTOM_INPUT_FOCUS_4: '#custom-input-focus-4',
  CUSTOM_RATE_INPUT: '.custom-rate-input',
  CUSTOM_INPUT_5: '#custom-input-5',
  CUSTOM_INPUT_4: '#custom-input-4',
  CUSTOM_INPUT_3: '#custom-input-3',
  RESET: '#reset',
  SNIPE: '#snipe-btn',
  SNIPE_LIST: '#snipe-list',
  CUSTOM_MODAL: '#custom-banner-modal',
  CUSTOM_LIST: '#custom-banner-select-list',
  CUSTOM_LIST_DESC: '#custom-banner-select-list label',
  CUSTOM_FOCUS: '#custom-banner-heroes',
  CUSTOM_SEARCH: '#custom-banner-search',
  CREATE_BANNER: '#create-banner',
  TABLE_FILTER_ITEM: '#table-filter .dropdown-item'
}
